import { Dimensions, StyleSheet } from 'react-native';
import { TAB_CARD_SPACING } from './constants';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');
const TAB_CARD_WIDTH = SCREEN_WIDTH * 0.75;
const TAB_CARD_HEIGHT = SCREEN_HEIGHT * 0.55;

export { SCREEN_WIDTH, SCREEN_HEIGHT, TAB_CARD_WIDTH, TAB_CARD_HEIGHT };

export const styles = StyleSheet.create({
  fullScreen: {
    flex: 1,
    backgroundColor: '#000',
  },
  safeArea: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  container: {
    flex: 1,
    paddingHorizontal: 12,
    paddingTop: 4,
    paddingBottom: 0,
    gap: 8,
  },
  webViewWrapper: {
    flex: 1,
    position: 'relative',
    overflow: 'hidden',
  },
  webView: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  startSurfaceOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 10,
  },
  bottomDockWrapper: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 5,
  },
  startSurface: {
    flex: 1,
    padding: 24,
    paddingTop: 60,
    gap: 16,
    justifyContent: 'flex-start',
    backgroundColor: '#f8fafc',
  },
  startSurfaceDark: {
    backgroundColor: '#1c1c1e',
  },
  startSubtitle: {
    fontSize: 14,
    color: '#475569',
  },
  startSubtitleDark: {
    color: '#a1a1aa',
  },
  quickLinkRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  quickLinkChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#2563eb',
  },
  quickLinkChipDark: {
    backgroundColor: '#3b82f6',
  },
  quickLinkText: {
    fontSize: 14,
    fontWeight: '600',
  },
  customLinkCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    padding: 16,
    gap: 10,
    backgroundColor: '#fff',
  },
  customLinkCardDark: {
    backgroundColor: '#2c2c2e',
    borderColor: '#3a3a3c',
  },
  customHelper: {
    fontSize: 12,
    color: '#64748b',
  },
  customInput: {
    borderWidth: 1,
    borderColor: '#d4dbe8',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 14,
    backgroundColor: '#f8fafc',
    color: '#0f172a',
  },
  customInputDark: {
    backgroundColor: '#1c1c1e',
    borderColor: '#3a3a3c',
    color: '#fff',
  },
  customSaveButton: {
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: 'center',
    backgroundColor: '#2563eb',
  },
  customSaveButtonDisabled: {
    opacity: 0.6,
  },
  customSaveLabel: {
    fontSize: 14,
    fontWeight: '600',
  },
  customFeedback: {
    fontSize: 12,
    color: '#0f172a',
  },
  ritualCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    padding: 16,
    gap: 8,
    backgroundColor: '#fff',
  },
  ritualCardDark: {
    backgroundColor: '#2c2c2e',
    borderColor: '#3a3a3c',
  },
  ritualRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  ritualText: {
    fontSize: 14,
    flex: 1,
  },
  loaderOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.05)',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  loaderText: {
    fontSize: 14,
    color: '#475569',
  },
  pullDownHint: {
    position: 'absolute',
    top: 80,
    left: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    zIndex: 10,
  },
  pullDownText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#475569',
  },
  bottomDock: {
    gap: 12,
    paddingBottom: 34,
    paddingTop: 12,
    paddingHorizontal: 12,
    overflow: 'hidden',
  },
  toolbar: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    paddingHorizontal: 4,
  },
  toolbarButton: {
    flex: 1,
    marginHorizontal: 4,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    alignItems: 'center',
  },
  toolbarButtonDisabled: {
    opacity: 0.4,
  },
  addressRow: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  input: {
    flex: 6,
    borderWidth: 0.5,
    borderColor: 'rgba(0, 0, 0, 0.1)',
    borderRadius: 30,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
  },
  switcherOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(15, 23, 42, 0.35)',
  },
  switcherPanel: {
    backgroundColor: '#fff',
    padding: 16,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    gap: 12,
  },
  switcherHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 60,
    paddingHorizontal: 20,
    paddingBottom: 16,
  },
  switcherAddButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#e0f2ff',
  },
  switcherAddLabel: {
    color: '#2563eb',
    fontSize: 13,
    fontWeight: '600',
  },
  switcherList: {
    gap: 10,
  },
  swipeTrack: {
    position: 'relative',
    overflow: 'hidden',
    borderRadius: 16,
  },
  swipeActionLeft: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 120,
    backgroundColor: '#ef4444',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 4,
  },
  swipeActionRight: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: 120,
    backgroundColor: '#ef4444',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 4,
  },
  swipeActionLabel: {
    fontSize: 13,
    color: '#fff',
    fontWeight: '500',
  },
  switcherCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#fff',
  },
  switcherCardActive: {
    borderColor: '#2563eb',
  },
  switcherCardBody: {
    flex: 1,
    gap: 4,
  },
  switcherCardTitle: {
    fontSize: 15,
    fontWeight: '600',
  },
  switcherCardSubtitle: {
    fontSize: 12,
    color: '#475569',
  },
  switcherCloseButton: {
    marginLeft: 12,
    padding: 6,
  },
  switcherHeaderBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 16,
  },
  switcherDoneButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  switcherDoneText: {
    fontSize: 17,
    color: '#007AFF',
    fontWeight: '600',
  },
  switcherTitle: {
    fontSize: 17,
    fontWeight: '600',
  },
  switcherAddBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  switcherScrollContent: {
    alignItems: 'center',
    paddingVertical: 20,
    paddingHorizontal: (SCREEN_WIDTH - SCREEN_WIDTH * TAB_CARD_SPACING) / 2,
  },
  tabCardWrapper: {
    width: SCREEN_WIDTH * TAB_CARD_SPACING,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabCard: {
    width: TAB_CARD_WIDTH,
    height: TAB_CARD_HEIGHT,
    borderRadius: 16,
    backgroundColor: '#fff',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
    borderWidth: 3,
    borderColor: 'transparent',
  },
  tabCardActive: {
    borderColor: '#007AFF',
  },
  tabCardDark: {
    backgroundColor: '#1c1c1e',
  },
  tabCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#f8fafc',
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  tabCardHeaderDark: {
    backgroundColor: '#2c2c2e',
    borderBottomColor: '#3a3a3c',
  },
  tabCardUrlBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginRight: 12,
  },
  tabCardUrl: {
    flex: 1,
    fontSize: 13,
    color: '#64748b',
  },
  tabCardContainer: {
    width: TAB_CARD_WIDTH,
    height: TAB_CARD_HEIGHT,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
  },
  tabCardContent: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 16,
    borderWidth: 2,
    borderColor: 'transparent',
    overflow: 'hidden',
  },
  tabCardContentActive: {
    borderColor: '#007AFF',
  },
  tabCardContentDark: {
    backgroundColor: '#1c1c1e',
  },
  tabCardPreview: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f8fafc',
    gap: 16,
    padding: 20,
  },
  tabCardPreviewDark: {
    backgroundColor: '#2c2c2e',
  },
  tabCardPreviewText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#334155',
    textAlign: 'center',
  },
  tabCardIconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#eff6ff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  tabCardFavicon: {
    width: 80,
    height: 80,
    borderRadius: 20,
    backgroundColor: '#f1f5f9',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  tabCardFaviconDark: {
    backgroundColor: '#374151',
  },
  tabCardDomain: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1e293b',
  },
  tabCardFullUrl: {
    fontSize: 13,
    color: '#94a3b8',
    textAlign: 'center',
    marginTop: 4,
  },
  tabCardCloseButton: {
    position: 'absolute',
    top: 12,
    right: 12,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  swipeHint: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    marginTop: 16,
  },
  swipeHintText: {
    fontSize: 13,
    color: '#94a3b8',
  },
  pageIndicator: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  pageIndicatorDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(255,255,255,0.3)',
  },
  pageIndicatorDotActive: {
    backgroundColor: '#fff',
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  switcherBottomBar: {
    alignItems: 'center',
    paddingVertical: 16,
    paddingBottom: 40,
    gap: 16,
  },
  switcherNewTabButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderRadius: 24,
  },
  switcherNewTabText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#007AFF',
  },
  bookmarksOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  bookmarksPanel: {
    flex: 1,
    backgroundColor: '#fff',
    paddingTop: 60,
    paddingBottom: 34,
  },
  bookmarksPanelDark: {
    backgroundColor: '#1c1c1e',
  },
  bookmarksHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 16,
    borderBottomWidth: 0.5,
    borderBottomColor: 'rgba(0, 0, 0, 0.1)',
  },
  bookmarksDoneButton: {
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  bookmarksDoneText: {
    fontSize: 17,
    color: '#007AFF',
    fontWeight: '600',
  },
  bookmarksTitle: {
    fontSize: 17,
    fontWeight: '600',
  },
  bookmarksAddButton: {
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  bookmarksAddButtonDisabled: {
    opacity: 0.5,
  },
  bookmarksList: {
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  bookmarksEmpty: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
    gap: 12,
  },
  bookmarksEmptyText: {
    fontSize: 17,
    fontWeight: '600',
    color: '#64748b',
  },
  bookmarksEmptyHint: {
    fontSize: 14,
    color: '#94a3b8',
    textAlign: 'center',
  },
  bookmarkItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 12,
    marginBottom: 8,
    backgroundColor: '#f8fafc',
    borderRadius: 12,
  },
  bookmarkItemDark: {
    backgroundColor: '#2c2c2e',
  },
  bookmarkContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  bookmarkTextContainer: {
    flex: 1,
    gap: 2,
  },
  bookmarkTitle: {
    fontSize: 15,
    fontWeight: '500',
  },
  bookmarkUrl: {
    fontSize: 12,
    color: '#64748b',
  },
  bookmarkDeleteButton: {
    padding: 8,
    marginLeft: 8,
  },
  settingsContent: {
    padding: 20,
    gap: 20,
  },
  settingSectionTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#64748b',
    marginBottom: 8,
    marginLeft: 4,
    textTransform: 'uppercase',
  },
  providerCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f8fafc',
    padding: 16,
    borderRadius: 16,
    gap: 12,
  },
  providerCardDark: {
    backgroundColor: '#2c2c2e',
  },
  providerIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#eef2ff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  providerInfo: {
    flex: 1,
    gap: 4,
  },
  providerName: {
    fontSize: 16,
    fontWeight: '600',
  },
  providerDesc: {
    fontSize: 12,
    color: '#64748b',
  },
  settingItem: {
    gap: 12,
  },
  settingLabel: {
    fontSize: 16,
    fontWeight: '600',
  },
  settingInput: {
    backgroundColor: '#f1f5f9',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 15,
    color: '#000',
  },
  settingInputDark: {
    backgroundColor: '#1e293b',
    color: '#fff',
  },
  settingHint: {
    fontSize: 13,
    color: '#64748b',
  },
  modelOption: {
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 8,
  },
  modelOptionDark: {
    backgroundColor: '#2c2c2e',
  },
  modelOptionSelected: {
    backgroundColor: '#eef2ff',
    borderWidth: 1,
    borderColor: '#4f46e5',
  },
  modelOptionContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modelOptionText: {
    fontSize: 15,
    fontWeight: '500',
  },
  summaryOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    zIndex: 1000,
  },
  summaryBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  summaryDrawer: {
    height: '50%',
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 10,
  },
  summaryDrawerDark: {
    backgroundColor: '#1c1c1e',
  },
  summaryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 0.5,
    borderBottomColor: 'rgba(0, 0, 0, 0.1)',
  },
  summaryTitle: {
    fontSize: 18,
    fontWeight: '700',
  },
  summaryHeaderButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  summaryShareButton: {
    padding: 4,
  },
  summaryCloseButton: {
    padding: 4,
  },
  summaryContentScroll: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  summaryLoading: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 60,
  },
  summaryLoadingText: {
    fontSize: 15,
    color: '#64748b',
  },
  summaryError: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 16,
    paddingVertical: 60,
  },
  summaryErrorText: {
    fontSize: 15,
    color: '#ef4444',
    textAlign: 'center',
  },
  summaryText: {
    fontSize: 16,
    lineHeight: 24,
    paddingBottom: 40,
  },
});
